### ISSUE TITLE
Crash Reporter continually showing up

### ISSUE THREAD

**Issue by ghivert** [sindresorhus/electron-reloader#20]
Hi!

When using the last version of Electron, after each reload/quit, I get a Crash Reporter saying the application did not quit properly.
Is there anything I can do?

**Comment by sindresorhus** [comment]
Please open an issue on https://github.com/electron/electron about this. This package just calls the Electron methods to relaunch the app:

https://github.com/sindresorhus/electron-reloader/blob/840f904c8aaf99433166e59444424ad0afbff8dd/index.js#L78-L79
