### ISSUE TITLE
How to solve the problem that fsevents.node in chokidar is compiled during the compilation phase of webpack production and packaging, isn't electron-reloader dynamically imported by require?

### ISSUE THREAD

**Issue by white-than-wood** [sindresorhus/electron-reloader#27]
<img width="1320" alt="image" src="https://user-images.githubusercontent.com/11425476/169479846-879c2b30-4ded-42b0-bd97-0928cccb916a.png">

<img width="727" alt="image" src="https://user-images.githubusercontent.com/11425476/169479789-0d66b52f-4bb7-4e29-b9ae-06430933eefb.png">

PS: I don't want to use webpack node-loader in production environment. How to fixed it?

**Comment by sindresorhus** [comment]
This is not the place to ask Webpack questions.

Try asking in https://github.com/webpack/webpack/issues
